[pytest]
# Diretório raiz
testpaths = 
    services/animal_service
    shared

# Padrão de arquivos de teste
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Cobertura
addopts = 
    -v
    --tb=short
    --strict-markers
    --cov=services/animal-service
    --cov=shared
    --cov-report=html
    --cov-report=term-missing

# Markers personalizados
markers =
    unit: Testes unitários (rápidos)
    integration: Testes de integração
    slow: Testes lentos
